### ISSUE TITLE
Incorrect distance computation in `get_logits`

### ISSUE THREAD

**Issue by danoneata** [SegoleneMartin/PADDLE#2]
Hello! The [current code for distance computation](https://github.com/SegoleneMartin/PADDLE/blob/master/src/methods/paddle.py#L34-L36) in the `get_logits` method reads as follows:
```python
logits = (
    -samples.matmul(self.w.transpose(1, 2))
    - 1 / 2 * (self.w**2).sum(2).view(n_tasks, 1, -1)
    - 1 / 2 * (samples**2).sum(2).view(n_tasks, -1, 1)
)
```
But it should rather be
```diff
logits = (
-    -samples.matmul(self.w.transpose(1, 2))
+    +samples.matmul(self.w.transpose(1, 2))
    - 1 / 2 * (self.w**2).sum(2).view(n_tasks, 1, -1)
    - 1 / 2 * (samples**2).sum(2).view(n_tasks, -1, 1)
)
```
because -½‖x - y‖² =〈x, y〉- ½‖x‖² - ½‖y‖². This means that the current implementation updates the centroids that are far away from the query points.

**Comment by SegoleneMartin** [comment]
Hello! Thanks. I fixed it. All the results in the paper were produced with the correct sign but I must have introduced this error while cleaning the code. A somewhat simpler and cleaner version of PADDLE can be fined in the repo transductive_CLIP.

**Comment by danoneata** [comment]
Thanks for the quick response and the follow-up clarification! Do you have a link to the `transductive_CLIP` repo?

**Comment by SegoleneMartin** [comment]
Sure, here: https://github.com/SegoleneMartin/transductive-CLIP

**Comment by danoneata** [comment]
Thank you!
